import Foundation
import CoreGraphics
import PolygoCore

/// A point in the unit square used by the handwriting guides and captures.
/// Keeping guide coordinates independent from a device's pixel size lets the
/// same exercise work on an iPhone, iPad, or Mac window.
public struct HandwritingPoint: Codable, Hashable, Sendable {
    public let x: Double
    public let y: Double

    public init(x: Double, y: Double) {
        self.x = min(1, max(0, x))
        self.y = min(1, max(0, y))
    }

    public init(_ point: CGPoint, in size: CGSize) {
        let width = max(size.width, 1)
        let height = max(size.height, 1)
        self.init(x: Double(point.x / width), y: Double(point.y / height))
    }

    public func point(in size: CGSize) -> CGPoint {
        CGPoint(x: x * size.width, y: y * size.height)
    }
}
/// One ordered stroke in a guide. The points are a teaching path (a simplified
/// stroke median), rather than an outline, so the UI can reveal the order
/// without pretending to perform OCR.
public struct HandwritingGuideStroke: Codable, Hashable, Sendable, Identifiable {
    public let id: Int
    public let points: [HandwritingPoint]
    public let label: String?

    public init(id: Int, points: [HandwritingPoint], label: String? = nil) {
        self.id = id
        self.points = points
        self.label = label
    }
}

/// A normalized, ordered guide for one Chinese character.
public struct HandwritingGuide: Codable, Hashable, Sendable, Identifiable {
    public let id: AssetID
    public let character: String
    public let viewBox: CGSizeValue
    public let strokes: [HandwritingGuideStroke]

    public init(
        id: AssetID,
        character: String,
        viewBox: CGSizeValue = CGSizeValue(width: 1, height: 1),
        strokes: [HandwritingGuideStroke]
    ) {
        self.id = id
        self.character = character
        self.viewBox = viewBox
        self.strokes = strokes.filter { $0.points.count >= 1 }
    }

    public var expectedStrokeCount: Int { strokes.count }
}

/// The first handwriting corpus shipped with the lesson content.
///
/// The three guides are simplified stroke medians from Make Me a Hanzi
/// (Arphic Public License, see Content/assets/handwriting/ARPHICPL.TXT),
/// generated by Tools/build_handwriting_guides.py. The same data is checked
/// into Content/assets/handwriting as JSON so content can reference it with a
/// real SHA-256 hash. Modified from the source on 2026-09-28: medians rescaled
/// into the unit square, simplified, and labelled with stroke type names.
public enum HandwritingGuideCatalog {
    public static let pendingAssetHash = "pending-writing-guide"

    public static func guide(for exercise: HandwritingExercise) -> HandwritingGuide? {
        guard exercise.guideAsset.kind == .handwritingGuide,
              exercise.guideAsset.sha256.caseInsensitiveCompare(pendingAssetHash) != .orderedSame else {
            return nil
        }
        guard let guide = guide(forCharacter: exercise.targetHanzi) else { return nil }
        guard guide.id == exercise.guideAsset.id else { return nil }
        return guide
    }

    public static func guide(forCharacter character: String) -> HandwritingGuide? {
        switch character {
        case "你": return ni
        case "我": return wo
        case "国": return guo
        default: return nil
        }
    }

    /// Decodes the checked-in guide format for integrations that resolve an
    /// AssetReference through ContentStore before constructing the view.
    public static func decode(data: Data) throws -> HandwritingGuide {
        try JSONDecoder().decode(HandwritingGuide.self, from: data)
    }

    // BEGIN GENERATED GUIDES (Tools/build_handwriting_guides.py)
    private static let ni = HandwritingGuide(
        id: AssetID(rawValue: "guide-hanzi-ni")!,
        character: "你",
        strokes: [
            HandwritingGuideStroke(id: 1, points: [
                HandwritingPoint(x: 0.348, y: 0.169),
                HandwritingPoint(x: 0.376, y: 0.21),
                HandwritingPoint(x: 0.337, y: 0.285),
                HandwritingPoint(x: 0.241, y: 0.424),
                HandwritingPoint(x: 0.153, y: 0.516)
            ], label: "撇"),
            HandwritingGuideStroke(id: 2, points: [
                HandwritingPoint(x: 0.313, y: 0.367),
                HandwritingPoint(x: 0.322, y: 0.459),
                HandwritingPoint(x: 0.3, y: 0.707),
                HandwritingPoint(x: 0.303, y: 0.771)
            ], label: "竖"),
            HandwritingGuideStroke(id: 3, points: [
                HandwritingPoint(x: 0.534, y: 0.156),
                HandwritingPoint(x: 0.565, y: 0.191),
                HandwritingPoint(x: 0.556, y: 0.22),
                HandwritingPoint(x: 0.476, y: 0.388),
                HandwritingPoint(x: 0.417, y: 0.466)
            ], label: "撇"),
            HandwritingGuideStroke(id: 4, points: [
                HandwritingPoint(x: 0.501, y: 0.388),
                HandwritingPoint(x: 0.65, y: 0.346),
                HandwritingPoint(x: 0.722, y: 0.337),
                HandwritingPoint(x: 0.746, y: 0.363),
                HandwritingPoint(x: 0.683, y: 0.444)
            ], label: "横钩"),
            HandwritingGuideStroke(id: 5, points: [
                HandwritingPoint(x: 0.558, y: 0.441),
                HandwritingPoint(x: 0.594, y: 0.481),
                HandwritingPoint(x: 0.59, y: 0.746),
                HandwritingPoint(x: 0.572, y: 0.78),
                HandwritingPoint(x: 0.483, y: 0.737)
            ], label: "竖钩"),
            HandwritingGuideStroke(id: 6, points: [
                HandwritingPoint(x: 0.455, y: 0.556),
                HandwritingPoint(x: 0.41, y: 0.685)
            ], label: "点"),
            HandwritingGuideStroke(id: 7, points: [
                HandwritingPoint(x: 0.68, y: 0.548),
                HandwritingPoint(x: 0.769, y: 0.634),
                HandwritingPoint(x: 0.786, y: 0.683)
            ], label: "点")
        ]
    )

    private static let wo = HandwritingGuide(
        id: AssetID(rawValue: "guide-hanzi-wo")!,
        character: "我",
        strokes: [
            HandwritingGuideStroke(id: 1, points: [
                HandwritingPoint(x: 0.458, y: 0.313),
                HandwritingPoint(x: 0.406, y: 0.31),
                HandwritingPoint(x: 0.314, y: 0.372),
                HandwritingPoint(x: 0.259, y: 0.395)
            ], label: "撇"),
            HandwritingGuideStroke(id: 2, points: [
                HandwritingPoint(x: 0.236, y: 0.488),
                HandwritingPoint(x: 0.288, y: 0.489),
                HandwritingPoint(x: 0.625, y: 0.402),
                HandwritingPoint(x: 0.68, y: 0.403)
            ], label: "横"),
            HandwritingGuideStroke(id: 3, points: [
                HandwritingPoint(x: 0.352, y: 0.369),
                HandwritingPoint(x: 0.385, y: 0.395),
                HandwritingPoint(x: 0.382, y: 0.713),
                HandwritingPoint(x: 0.366, y: 0.751),
                HandwritingPoint(x: 0.292, y: 0.715)
            ], label: "竖钩"),
            HandwritingGuideStroke(id: 4, points: [
                HandwritingPoint(x: 0.178, y: 0.642),
                HandwritingPoint(x: 0.227, y: 0.655),
                HandwritingPoint(x: 0.484, y: 0.542)
            ], label: "提"),
            HandwritingGuideStroke(id: 5, points: [
                HandwritingPoint(x: 0.484, y: 0.173),
                HandwritingPoint(x: 0.52, y: 0.209),
                HandwritingPoint(x: 0.52, y: 0.313),
                HandwritingPoint(x: 0.545, y: 0.463),
                HandwritingPoint(x: 0.578, y: 0.57),
                HandwritingPoint(x: 0.628, y: 0.67),
                HandwritingPoint(x: 0.709, y: 0.766),
                HandwritingPoint(x: 0.738, y: 0.786),
                HandwritingPoint(x: 0.771, y: 0.794),
                HandwritingPoint(x: 0.798, y: 0.668)
            ], label: "斜钩"),
            HandwritingGuideStroke(id: 6, points: [
                HandwritingPoint(x: 0.665, y: 0.481),
                HandwritingPoint(x: 0.676, y: 0.518),
                HandwritingPoint(x: 0.619, y: 0.601),
                HandwritingPoint(x: 0.564, y: 0.648),
                HandwritingPoint(x: 0.455, y: 0.7)
            ], label: "撇"),
            HandwritingGuideStroke(id: 7, points: [
                HandwritingPoint(x: 0.613, y: 0.248),
                HandwritingPoint(x: 0.686, y: 0.281),
                HandwritingPoint(x: 0.71, y: 0.308)
            ], label: "点")
        ]
    )

    private static let guo = HandwritingGuide(
        id: AssetID(rawValue: "guide-hanzi-guo")!,
        character: "国",
        strokes: [
            HandwritingGuideStroke(id: 1, points: [
                HandwritingPoint(x: 0.269, y: 0.221),
                HandwritingPoint(x: 0.294, y: 0.251),
                HandwritingPoint(x: 0.3, y: 0.316),
                HandwritingPoint(x: 0.292, y: 0.552),
                HandwritingPoint(x: 0.271, y: 0.728),
                HandwritingPoint(x: 0.275, y: 0.784)
            ], label: "竖"),
            HandwritingGuideStroke(id: 2, points: [
                HandwritingPoint(x: 0.327, y: 0.269),
                HandwritingPoint(x: 0.337, y: 0.256),
                HandwritingPoint(x: 0.37, y: 0.25),
                HandwritingPoint(x: 0.664, y: 0.21),
                HandwritingPoint(x: 0.697, y: 0.214),
                HandwritingPoint(x: 0.723, y: 0.238),
                HandwritingPoint(x: 0.747, y: 0.685),
                HandwritingPoint(x: 0.737, y: 0.75),
                HandwritingPoint(x: 0.743, y: 0.802)
            ], label: "横折"),
            HandwritingGuideStroke(id: 3, points: [
                HandwritingPoint(x: 0.388, y: 0.362),
                HandwritingPoint(x: 0.436, y: 0.366),
                HandwritingPoint(x: 0.583, y: 0.334),
                HandwritingPoint(x: 0.618, y: 0.335)
            ], label: "横"),
            HandwritingGuideStroke(id: 4, points: [
                HandwritingPoint(x: 0.38, y: 0.498),
                HandwritingPoint(x: 0.418, y: 0.505),
                HandwritingPoint(x: 0.554, y: 0.48),
                HandwritingPoint(x: 0.602, y: 0.484)
            ], label: "横"),
            HandwritingGuideStroke(id: 5, points: [
                HandwritingPoint(x: 0.473, y: 0.377),
                HandwritingPoint(x: 0.495, y: 0.396),
                HandwritingPoint(x: 0.498, y: 0.458),
                HandwritingPoint(x: 0.495, y: 0.587),
                HandwritingPoint(x: 0.482, y: 0.605)
            ], label: "竖"),
            HandwritingGuideStroke(id: 6, points: [
                HandwritingPoint(x: 0.348, y: 0.641),
                HandwritingPoint(x: 0.391, y: 0.644),
                HandwritingPoint(x: 0.594, y: 0.611),
                HandwritingPoint(x: 0.657, y: 0.623)
            ], label: "提"),
            HandwritingGuideStroke(id: 7, points: [
                HandwritingPoint(x: 0.613, y: 0.51),
                HandwritingPoint(x: 0.662, y: 0.539),
                HandwritingPoint(x: 0.682, y: 0.567)
            ], label: "点"),
            HandwritingGuideStroke(id: 8, points: [
                HandwritingPoint(x: 0.301, y: 0.764),
                HandwritingPoint(x: 0.313, y: 0.751),
                HandwritingPoint(x: 0.35, y: 0.747),
                HandwritingPoint(x: 0.654, y: 0.722),
                HandwritingPoint(x: 0.703, y: 0.727)
            ], label: "横")
        ]
    )
    // END GENERATED GUIDES
}
